# Convert JAX npz to safetensors

In [1]:
import os
import json
import torch
import argparse
import numpy as np
from huggingface_hub import login
import os
hf_token = os.getenv('HF_TOKEN')
login(token=hf_token)
import transformers

import struct
def convert_void_array(arr):
    """Convert void array to float32."""
    # Convert void array to bytes
    flat_bytes = arr.tobytes()
    # Interpret each 2-byte chunk as a bfloat16
    num_elements = len(flat_bytes) // 2
    floats = []
    
    for i in range(num_elements):
        # Extract 2 bytes and convert to float32
        two_bytes = flat_bytes[i*2:(i+1)*2]
        # Pad to 4 bytes (float32)
        padded = two_bytes + b'\x00\x00'
        # Convert to float32
        val = struct.unpack('f', padded)[0]
        floats.append(val)
    
    # Reshape to original shape
    return np.array(floats, dtype=np.float32).reshape(arr.shape)


jax_ckpt = "/data/austin/jax_ckpts"
output_dir = "/data/austin/jax_ckpts"
model_id = "google/paligemma-3b-pt-224"
args = argparse.Namespace(
    jax_ckpt=jax_ckpt,
	output_dir=output_dir,
	model_id=model_id,
)

/data/austin/miniconda3/envs/jax/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [4]:
print(f"Loading JAX checkpoint from {args.jax_ckpt}")
npz_path = os.path.join(args.jax_ckpt,"hf_state_dict.npz")
np_file = np.load(npz_path)

print(f"Converting JAX checkpoint dtype to float32")
params = {}
for k, v in np_file.items():
	if v.dtype == np.dtype('|V2'):
		print(f"Converting {k} from |V2 to float32")
		params[k] = torch.tensor(convert_void_array(v))
	else:
		params[k] = torch.tensor(v)

# check params
print(f"Verifying all params are float32")
for k, v in params.items():
	if v.dtype != torch.float32:
		print(k, v.dtype)

Loading JAX checkpoint from /data/austin/jax_ckpts
Converting JAX checkpoint dtype to float32
Converting vision_tower.vision_model.embeddings.position_embedding.weight from |V2 to float32
Verifying all params are float32


In [5]:
# Load config and model
config_path = os.path.join(os.path.dirname(npz_path), "hf_config.json")
print(f"Loading config from {config_path}")
with open(config_path) as f:
	config_dict = json.load(f)
config = transformers.PaliGemmaConfig(**config_dict)
model = transformers.PaliGemmaForConditionalGeneration(config)
print(f"Loaded model from config: {config}")


for k,v in model.state_dict().items():
	if not k in params:
		print(f"WARNING: {k} not found in JAX checkpoint")
		continue

Loading config from /data/austin/jax_ckpts/hf_config.json
Loaded model from config: PaliGemmaConfig {
  "_attn_implementation_autoset": true,
  "_name_or_path": "google/paligemma-3b-pt-224",
  "_vocab_size": 257216,
  "architectures": [
    "PaliGemmaForConditionalGeneration"
  ],
  "bos_token_id": 2,
  "eos_token_id": 1,
  "hidden_size": 2048,
  "image_token_index": 256127,
  "model_type": "paligemma",
  "pad_token_id": 0,
  "projection_dim": 2048,
  "text_config": {
    "hidden_size": 2048,
    "intermediate_size": 16384,
    "model_type": "gemma",
    "num_attention_heads": 8,
    "num_hidden_layers": 18,
    "num_image_tokens": 196,
    "num_key_value_heads": 1,
    "torch_dtype": "float32",
    "vocab_size": 256128
  },
  "torch_dtype": "float32",
  "transformers_version": "4.48.1",
  "vision_config": {
    "hidden_size": 768,
    "intermediate_size": 3072,
    "model_type": "siglip_vision_model",
    "num_attention_heads": 12,
    "num_hidden_layers": 12,
    "num_image_tokens": 

In [6]:
print("Loading state dict into model")
missing, unexpected = model.load_state_dict(params, strict=False)
print(f"Missing keys: {missing}")
print(f"Unexpected keys: {unexpected}")

print(f"Saving model to {args.output_dir}")
model.save_pretrained(args.output_dir)


Loading state dict into model
Missing keys: []
Unexpected keys: []
Saving model to /data/austin/jax_ckpts


# Load model from safetensors

In [ ]:
import torch
import requests
from PIL import Image
import transformers

model_path = "/data/austin/jax_ckpts/cambrian_gemma_datacomp_recap-alt-10M+datacomp_recap-recap-10M+datacomp_dense-ram_owlvitv2_20250112-07-matched_mix-divdesF_divdetF_10epoch_01-19_0123"
model = transformers.PaliGemmaForConditionalGeneration.from_pretrained(model_path)
refer_id = "google/paligemma-3b-pt-224"
processor = transformers.PaliGemmaProcessor.from_pretrained(refer_id)
# transformers.PaliGemmaProcessor.from_pretrained(model_path)
processor.tokenizer.vocab_size, model.state_dict()["language_model.lm_head.weight"].shape,model.state_dict()["language_model.model.embed_tokens.weight"].shape


In [ ]:
# change the lm_head to match the vocab size
corrected_state_dict = model.state_dict()
corrected_state_dict["language_model.lm_head.weight"] = corrected_state_dict["language_model.lm_head.weight"][:processor.tokenizer.vocab_size]
corrected_state_dict["language_model.model.embed_tokens.weight"] = corrected_state_dict["language_model.model.embed_tokens.weight"][:processor.tokenizer.vocab_size]
model.load_state_dict(corrected_state_dict)


In [ ]:
url = "https://huggingface.co/datasets/huggingface/documentation-images/resolve/main/transformers/tasks/car.jpg?download=true"
image = Image.open(requests.get(url, stream=True).raw)
prompt = "caption en"
model_inputs = processor(text=prompt, images=image, return_tensors="pt")
input_len = model_inputs["input_ids"].shape[-1]

In [ ]:
with torch.inference_mode():
    generation = model.generate(**model_inputs, max_new_tokens=100, do_sample=False)
    generation = generation[0][input_len:]
    decoded = processor.decode(generation, skip_special_tokens=True)
    print(decoded)


# CambrianGemma loading

In [1]:
%load_ext autoreload
%autoreload 2
import os
import sys
sys.path.append("/data/austin/cambrian")

from cambrian.model import CambrianGemmaForCausalLM, CambrianGemmaConfig
from transformers import PaliGemmaForConditionalGeneration, PaliGemmaProcessor, PaliGemmaConfig
                
my_ckpt_path = "/data/austin/paligemma_jax_to_hf"
cambrian_ckpt_path = "/data/austin/cambrian_gemma_jax_to_hf"
# Load the model and processor
my_model = PaliGemmaForConditionalGeneration.from_pretrained(my_ckpt_path)
my_model.language_model.model.mm_projector = my_model.multi_modal_projector.linear
tpu_state_dict = my_model.language_model.state_dict()
for key in tpu_state_dict.keys():
    print(key, tpu_state_dict[key].mean().item())

/data/austin/miniconda3/envs/cambrian/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


10:20:25 __init__.py:40 [I] → Notebook logger initialized.


`config.hidden_act` is ignored, you should use `config.hidden_activation` instead.
Gemma's activation function will be set to `gelu_pytorch_tanh`. Please, use
`config.hidden_activation` if you want to override this behaviour.
See https://github.com/huggingface/transformers/pull/29402 for more details.
Loading checkpoint shards: 100%|██████████| 3/3 [00:01<00:00,  2.39it/s]


model.embed_tokens.weight 0.001709498232230544
model.layers.0.self_attn.q_proj.weight 1.1955980880884454e-05
model.layers.0.self_attn.k_proj.weight -1.4495802133751567e-05
model.layers.0.self_attn.v_proj.weight 6.956436845939606e-05
model.layers.0.self_attn.o_proj.weight -8.572314072807785e-06
model.layers.0.mlp.gate_proj.weight 6.777975795557722e-05
model.layers.0.mlp.up_proj.weight -2.9926466140750563e-06
model.layers.0.mlp.down_proj.weight -2.4211203708546236e-06
model.layers.0.input_layernorm.weight 1.1274532079696655
model.layers.0.post_attention_layernorm.weight 0.8050136566162109
model.layers.1.self_attn.q_proj.weight 4.189802439213963e-06
model.layers.1.self_attn.k_proj.weight -1.4787511645408813e-05
model.layers.1.self_attn.v_proj.weight -4.616056685335934e-05
model.layers.1.self_attn.o_proj.weight -1.3656968803843483e-05
model.layers.1.mlp.gate_proj.weight 1.8108215954271145e-05
model.layers.1.mlp.up_proj.weight -5.867585969099309e-06
model.layers.1.mlp.down_proj.weight -3.15

In [ ]:
# cambrian_init_config = CambrianGemmaConfig.from_pretrained("google/gemma-2b")
cambrian_init_config = PaliGemmaConfig.from_pretrained(my_ckpt_path).text_config
# initialize Cambrian Gemma Model
cambrian_init_config.vocab_size = 256_192
cambrian_init_config.mm_vision_tower_aux_list = [os.path.join(cambrian_ckpt_path, 'bv_siglip_gemma_stage_0_pt.npz'),]
cambrian_init_config.mm_vision_tower_aux_token_len_list = [196,]

cambrian_init_config.mm_use_im_start_end = False
cambrian_init_config.mm_use_im_patch_token = False

cambrian_init_config.mm_vision_select_feature = "patch"
cambrian_init_config.mm_vision_select_layer = -1

cambrian_init_config.query_num_list = None
cambrian_init_config.mm_projector_type = 'linear'
cambrian_init_config.mm_hidden_size = 768
cambrian_init_config.mm_image_size = 224
cambrian_init_config.image_token_len = 196

print(f"Initializing Cambrian Gemma Model with config: {cambrian_init_config}")
cambrian_model = CambrianGemmaForCausalLM.from_pretrained(
		cambrian_ckpt_path,
		config=cambrian_init_config,
		cache_dir=None,
		torch_dtype=None,
)

print("Loading TPU state dict into Cambrian model")
cambrian_model.load_state_dict(tpu_state_dict, strict=False)
for key in cambrian_model.state_dict().keys():
		print(key, cambrian_model.state_dict()[key].mean().item())

10:20:45 builder.py:106 [I] → Loading **SigLIP CLIP** Vision Tower: /data/austin/cambrian_gemma_jax_to_hf/bv_siglip_gemma_stage_0_pt.npz
10:20:45 base_encoder.py:44 [W] → Unfreezing MM Vision Tower: False


Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

Loading checkpoint shards: 100%|██████████| 3/3 [00:01<00:00,  2.71it/s]


model.image_newline 35143469236224.0
model.embed_tokens.weight 0.001709498232230544
model.layers.0.self_attn.q_proj.weight 1.1955980880884454e-05
model.layers.0.self_attn.k_proj.weight -1.4495802133751567e-05
model.layers.0.self_attn.v_proj.weight 6.956436845939606e-05
model.layers.0.self_attn.o_proj.weight -8.572314072807785e-06
model.layers.0.mlp.gate_proj.weight 6.777975795557722e-05
model.layers.0.mlp.up_proj.weight -2.9926466140750563e-06
model.layers.0.mlp.down_proj.weight -2.4211203708546236e-06
model.layers.0.input_layernorm.weight 1.1274532079696655
model.layers.0.post_attention_layernorm.weight 0.8050136566162109
model.layers.1.self_attn.q_proj.weight 4.189802439213963e-06
model.layers.1.self_attn.k_proj.weight -1.4787511645408813e-05
model.layers.1.self_attn.v_proj.weight -4.616056685335934e-05
model.layers.1.self_attn.o_proj.weight -1.3656968803843483e-05
model.layers.1.mlp.gate_proj.weight 1.8108215954271145e-05
model.layers.1.mlp.up_proj.weight -5.867585969099309e-06
mode

In [5]:
# Save the cambrian_model
state_dict = {}
for k, v in cambrian_model.state_dict().items():
		state_dict[k] = v
cambrian_model.save_pretrained(cambrian_ckpt_path, state_dict=state_dict)
print(f"Saved converted HF cambrian_model to {cambrian_ckpt_path}")

# Save the cambrian processor (same as my processor)
processor = PaliGemmaProcessor.from_pretrained(my_ckpt_path, use_fast=False)
processor.save_pretrained(cambrian_ckpt_path)
print(f"Saved converted HF processor to {cambrian_ckpt_path}")

Saved converted HF cambrian_model to /data/austin/cambrian_gemma_jax_to_hf


Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


Saved converted HF processor to /data/austin/cambrian_gemma_jax_to_hf


Example:
(cambrian) [austin@sn4622121577 paligemma_jax_to_hf]$ gsutil cat gs://tsb-data-01/mllm/1stage_cambrian_qwen2_7b_siglip256-last/config.json
{
  "_name_or_path": "/mnt/disks/cambrian_s/checkpoints/Qwen2-7B-Instruct",
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "connector_depth": 1,
  "connector_only": true,
  "do_sample": true,
  "eos_token_id": 151645,
  "freeze_mm_mlp_adapter": false,
  "hidden_act": "silu",
  "hidden_size": 3584,
  "image_aspect_ratio": "pad",
  "image_position": 14,
  "image_token_len": 256,
  "initializer_range": 0.02,
  "intermediate_size": 18944,
  "max_position_embeddings": 32768,
  "max_window_layers": 28,
  "mm_hidden_size": 1152,
  "mm_projector_lr": null,
  "mm_projector_type": "mlp2x_gelu",
  "mm_use_im_patch_token": false,
  "mm_use_im_start_end": false,
  "mm_vision_sampler_lr": null,
  "mm_vision_select_feature": "patch",
  "mm_vision_select_layer": -2,
  "mm_vision_tower_aux_list": [
    "google/siglip-so400m-patch14-384"
  ],
  "mm_vision_tower_aux_token_len_list": [
    256
  ],
  "mm_vision_tower_lr": null,
  "model_type": "cambrian_qwen",
  "num_attention_heads": 28,
  "num_hidden_layers": 28,
  "num_key_value_heads": 4,
  "num_query_group": 1,
  "query_num_list": [
    576
  ],
  "rms_norm_eps": 1e-06,
  "rope_scaling": null,
  "rope_theta": 1000000.0,
  "sliding_window": 131072,
  "tie_word_embeddings": false,
  "tokenizer_model_max_length": 1024,
  "tokenizer_padding_side": "right",
  "torch_dtype": "bfloat16",
  "transformers_version": "4.37.0",
  "tune_mm_mlp_adapter": false,
  "unfreeze_mm_vision_tower": false,
  "use_cache": true,
  "use_mm_proj": true,
  "use_sliding_window": false,
  "video_max_frames": 0,
  "vision_hidden_size": 1024,
  "vision_tower_aux_token_len_list": [
    256
  ],
  "vocab_size": 152064
}

# Consistency Checking: Cambrian Gemma vs. My HF model

In [ ]:
%load_ext autoreload
%autoreload 2
import os
import sys
sys.path.append("/data/austin/cambrian")
import torch
import requests
from PIL import Image

from cambrian.model.builder import load_pretrained_model
from cambrian.model import CambrianGemmaForCausalLM, CambrianGemmaConfig
from transformers import PaliGemmaForConditionalGeneration, PaliGemmaProcessor

import argparse
from eval.eval.docvqa.docvqa_eval import process
cambrian_args = argparse.Namespace(
    question_extension="Give the short answer directly.",
    conv_mode="vicuna_v1",
    temperature=0,
    top_p=None,
    num_beams=1,
    max_new_tokens=30,
)


# Load the model and processor
my_ckpt_path = "/data/austin/paligemma_jax_to_hf"
print(f"Loading model and processor from {my_ckpt_path}")
my_model = PaliGemmaForConditionalGeneration.from_pretrained(my_ckpt_path)
my_processor = PaliGemmaProcessor.from_pretrained(my_ckpt_path, use_fast=False)

# import open_clip
# official_model, official_processor = open_clip.create_model_from_pretrained("ViT-B-16-SigLIP",pretrained='webli')

cambrian_ckpt_path = "/data/austin/cambrian_gemma_jax_to_hf"
print(f"Loading model and processor from {cambrian_ckpt_path}")
cambrian_tokenizer, cambrian_model, cambrian_image_processor, context_len = load_pretrained_model(cambrian_ckpt_path, None, "cambrian_gemma_jax_to_hf")



/data/austin/miniconda3/envs/cambrian/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


11:16:42 __init__.py:40 [I] → Notebook logger initialized.
11:16:44 config.py:54 [I] → PyTorch version 2.2.0 available.
Loading model and processor from /data/austin/paligemma_jax_to_hf


`config.hidden_act` is ignored, you should use `config.hidden_activation` instead.
Gemma's activation function will be set to `gelu_pytorch_tanh`. Please, use
`config.hidden_activation` if you want to override this behaviour.
See https://github.com/huggingface/transformers/pull/29402 for more details.
Loading checkpoint shards: 100%|██████████| 3/3 [00:01<00:00,  2.14it/s]
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


Loading model and processor from /data/austin/cambrian_gemma_jax_to_hf


Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
You are using a model of type gemma to instantiate a model of type cambrian_gemma. This is not supported for all configurations of models and can yield errors.


11:16:46 builder.py:106 [I] → Loading **SigLIP CLIP** Vision Tower: /data/austin/cambrian_gemma_jax_to_hf/bv_siglip_gemma_stage_0_pt.npz
11:16:46 base_encoder.py:44 [W] → Unfreezing MM Vision Tower: False


Loading checkpoint shards: 100%|██████████| 3/3 [00:01<00:00,  1.84it/s]


11:16:50 factory.py:312 [I] → Loaded ViT-B-16-SigLIP model config.
11:16:52 factory.py:399 [I] → Loading pretrained ViT-B-16-SigLIP weights (/data/austin/cambrian_gemma_jax_to_hf/bv_siglip_gemma_stage_0_pt.npz).
HELLO! I changed the load_checkpoint function!!!!


In [8]:
# url = "https://huggingface.co/datasets/huggingface/documentation-images/resolve/main/transformers/tasks/car.jpg?download=true"
# image = Image.open(requests.get(url, stream=True).raw)
# prompt = "What is the color of the car in the image?"

image_path = "/data/austin/tmp_img.png"
image = Image.open(image_path).convert("RGB")
prompt = 'What is the dividend payout in 2012?'
my_model_inputs = my_processor(text=prompt, images=image, return_tensors="pt")
input_len = my_model_inputs["input_ids"].shape[-1]
print(f"my_model_inputs.pixel_values with shape {my_model_inputs.pixel_values.shape}: \n{my_model_inputs.pixel_values[0,0,:3,:3]}")

cambrian_input_ids, cambrian_image_tensor, cambrian_image_sizes, cambrian_prompt = process({"question": prompt, "image": image}, cambrian_args, cambrian_tokenizer, cambrian_image_processor, cambrian_model.config)

my_model_inputs.pixel_values with shape torch.Size([1, 3, 224, 224]): 
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [9]:
my_model_inputs['pixel_values'] = cambrian_image_tensor[0].cpu()
print(f"modified my_model_inputs['pixel_values'] with shape {my_model_inputs['pixel_values'].shape}: \n{my_model_inputs['pixel_values'][0,0,:3,:3]}")

modified my_model_inputs['pixel_values'] with shape torch.Size([1, 3, 224, 224]): 
tensor([[-0.00392151, -0.00392151, -0.00392151],
        [-0.00392151, -0.00392151, -0.00392151],
        [-0.00392151, -0.00392151, -0.00392151]], dtype=torch.float16)


In [41]:
with torch.inference_mode():
    output = my_model.generate(**my_model_inputs, max_new_tokens=30, do_sample=False, temperature=0)
    generation = output[0][input_len:]
    decoded = my_processor.decode(generation, skip_special_tokens=False)
    print(f"Generated: {decoded}\n")

modeling_paligemma: my selected_image_feature with shape torch.Size([1, 196, 768]): 
tensor([[ 2.0099380016,  0.9100277424, -1.3489538431],
        [ 3.7345747948,  0.5945704579, -1.8425179720]]), mean: -0.0005179576692171395
modeling_paligemma: my image_features with shape torch.Size([1, 196, 2048]): 
tensor([[-3.9489417076, -4.6547460556, -0.9496644735],
        [-2.6995458603, -3.9559066296, -0.3158839941]]), mean: 0.009562659077346325
modeling_paligemma: my inputs_embeds with shape torch.Size([1, 210, 2048]): 
tensor([[-0.0872601122, -0.1028563306, -0.0209848192],
        [-0.0596521012, -0.0874140114, -0.0069801160]]), mean: 0.00025292433565482497
modeling_gemma: inputs_embeds with shape torch.Size([1, 210, 2048]): tensor([[[-8.7260112166e-02, -1.0285633057e-01, -2.0984819159e-02,
           ...,  1.9950972870e-02, -1.2629355490e-01,
          -9.4053655863e-02],
         [-5.9652101249e-02, -8.7414011359e-02, -6.9801160134e-03,
           ..., -1.9955241587e-03, -1.0194680095e-01

In [7]:
# # cambrian_input_ids = cambrian_input_ids.to(device='cuda', non_blocking=True)
# with torch.inference_mode():
# 		output_ids = cambrian_model.generate(
# 				cambrian_input_ids,
# 				images=cambrian_image_tensor,
# 				image_sizes=cambrian_image_sizes,
# 				do_sample=True if args.temperature > 0 else False,
# 				temperature=args.temperature,
# 				top_p=args.top_p,
# 				num_beams=args.num_beams,
# 				max_new_tokens=args.max_new_tokens,
# 				use_cache=False)